# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wandbtocsv',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/wandbtocsv',
                'lib_path': 'wandbtocsv'},
  'syms': {'wandbtocsv.core': {'wandbtocsv.core.fetch_runs': ('core.html#fetch_runs', 'wandbtocsv/core.py')}}}
